categories: [Sequence Analysis]
description: A test tool
long_description: |
  Just a test tool
homepage_url: https://github.com/galaxyproject
name: test
owner: bernt-matthias
remote_repository_url: https://github.com/bernt-matthias/galaxy-tool-repository-template/tree/master/tools/example/
